### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by shadow-identity** [d-ganchar/flask_request_validator#21]
Hello,
what is 'VIEW' parameter type? What's the difference between VIEW and GET?

**Comment by d-ganchar** [comment]
Hello. 
Thanks for the comment.

Maybe is not good way... I did not decide how to proceed further.
VIEW param is argument for view. FlaskRequest doesn't store all GET parameters in one property.
So if we have route

```
@app.route('/user/<string:uuid>/', methods=['POST'])
def route(user):
     # user here will VIEW(part of path) param
```

In this case we will have next query string _host/user/uuid1_. _user_ is storing in _request.view_args_.
Let's consider the next router _host/user/uuid1?user2=uuid2&key=test_. _key_ and _user2_ is storing in _request.args_. Currently is GET param. You can see [get_request_value](https://github.com/d-ganchar/flask_request_validator/blob/master/flask_request_validator/validator.py#L135) for better understanding.
By the way, right now _POST param_ works only for form data(_request.form_), but if we will send raw json in body validation will not work.

**Comment by d-ganchar** [comment]
@shadow-identity I updated the docs. You can check it.
