### ISSUE TITLE
Deep inspection into complex JSON objects

### ISSUE THREAD

**Issue by Cruuncher** [d-ganchar/flask_request_validator#36]
Given the following JSON body of a request:
```
{
    "outer": {
        "inner": 5
    }
}
```

How do I validate the field inner? There doesn't seem to be any examples covering this.

**Comment by d-ganchar** [comment]
@Cruuncher at the moment there are no possibility to validate embedded json. This is good feature, but need to implement it. As fast solution you can create custom validator and use [jsonschema](https://python-jsonschema.readthedocs.io/en/latest/). Just an example:

```
class MyRule(AbstractRule):

    def validate(self, value):
        try:
             validate(value, your_schema)
        except ValidationError as e:
             # return errors
```

**Comment by Cruuncher** [comment]
@d-ganchar Do you have an idea of how you'd like this to be implemented from a user perspective? I was considering doing an implementation and opening a PR. 

As a first idea I was going to allow using dot syntax to deep reference fields, but that's technically a breaking change. So I considered making a JSONDEEP type. 

Let me know your thoughts

**Comment by d-ganchar** [comment]
@Cruuncher thanks. I will think about it. I'll give you answer after 2 weeks(after vacation).

**Comment by d-ganchar** [comment]
@Cruuncher I thought about your proposal. Here is a vision. This is just a vision and you can suggest anything. I think we need to use **jsonschema** and new `Param` of validation(as example `SchemaParam`):

```
from jsonschema import Draft4Validator

class SchemaParam(object):

    def __init__(self, schema):
        self._schema = schema
        self._validator = Draft4Validator(self._schema)

    def validate(self):
        errors = sorted(self._validator.iter_errors(request.json), key=lambda e: e.path)
        return [str(i) for i in errors], request.json
```

An example of endpoint:

```
schema = {
        'type': 'object',
        'properties': {
            'price': {'type': 'number'},
            'name': {'type': 'string'},
        },
        'additionalProperties': False
}

@app.route('/schema', methods=['POST'])
@validate_params(SchemaParam(schema))
def schema_route(data):
    return 'ok'
```

We need to add some condition to `__get_errors`:

```
       if isinstance(param, SchemaParam):
             ...
```

In this case we won't have type conversion, but we can use `json-schema` for validation. What do you think?

**Comment by LostInDarkMath** [comment]
I think this is a good use case for third-party librarys. There are lots of type checkers for python. For example [pedantic](https://github.com/LostInDarkMath/pedantic-python-decorators) can do this. Working example:

```python
from typing import Dict

from flask_request_validator import AbstractRule
from pedantic.check_types import _assert_value_matches_type
from pedantic.exceptions import PedanticTypeCheckException


class DeepJson(AbstractRule):
    def __init__(self, expected_type):
        self._expected_type = expected_type

    def validate(self, value):
        errors = []

        try:
            _assert_value_matches_type(value=value, type_=self._expected_type, type_vars={}, err='')
        except PedanticTypeCheckException as ex:
            errors.append(f'invalid value: "{value}" does not have type "{self._expected_type}"')

        return value, errors


if __name__ == '__main__':
    rule = DeepJson(expected_type=Dict[str, Dict[str, int]])

    print(rule.validate({'a': {'b': 1, 'c': 42}}))
    # out: ({'a': {'b': 1, 'c': 42}}, [])
    # this means no errors

    print(rule.validate({'a': {'b': 1, 'c': 42.0}}))
    # out: ({'a': {'b': 1, 'c': 42.0}}, ['invalid value: "{\'a\': {\'b\': 1, \'c\': 42.0}}" does not have type "typing.Dict[str, typing.Dict[str, int]]"'])
```

But in my opinion the `Flask-Request-Validator` should not depend on this third-party-libraries. I like how small it is and the fact that is has no dependencies expect for Flask. And as you can see, it is very easy to expand the functionality.

**Comment by d-ganchar** [comment]
@LostInDarkMath `DeepJson` will be good feature _from box_. But I'm thinking about another nuance. Look at current format:

```
@app.route('/person')
@validate_params(
    Param('first_name', GET, str, rules=name_rule),
    Param('streets', GET, list),
    Param('coutry', GET, str, rules=[Enum('Germany')]),
    Param('meta', GET, dict), 
)
def example(first_name, streets, city, meta):
    # ...
```

I don't like a lot of arguments in functions. I believe that schema/descriptions parameters is better to move somewhere and route should works only with valid _MetaModel_. Just an example of my vision:

```
class ValidRequest:
       token: str
       cost: float
       # a lot of fields...

@app.route('/example')
@validate(ValidRequest, FieldMapper) 
def example(valid_request: ValidRequest):
      pass
```

In this case routes will be cleaner. So I think `DeepJson` is necessary functionality but it not quite suitable for the current `@validate_request`.
By the way I thought about one more thing. In some cases we need to use other API for validation and use API result inside route. It would be nice to provide such functionality after basic validators. Example:

```
# somewhere inside custom rule after all validators...
container = requests.get(valid_request.token).json()
if container['status'] in ('dead', 'exited', 'restarting'):
     errors.append('error')
else:
     move_to_route('container', container)

# get container inside route when request is valid 
@app.route('/example')
@validate(ValidRequest, FieldMapper) 
def example(valid_request: ValidRequest):
      valid_request.get('container').status
```

**Comment by LostInDarkMath** [comment]
I'm a fan of these `Param` arguments even if there are lots of. Simply because they are the most important part of API documentation for me. Unlike Swagger, docstrings or something like that, they are always up-to-date and on the point. Since complex rules can be grouped together in custom rules, its always easy to read.

**Comment by d-ganchar** [comment]
> I'm a fan of these `Param` arguments even if there are lots of. Simply because they are the most important part of API documentation for me. Unlike Swagger, docstrings or something like that, they are always up-to-date and on the point. Since complex rules can be grouped together in custom rules, its always easy to read.

I did not suggest deleting the current approach ) 
I need to think about my previous comment. Let me know please if you have any thoughts.

**Comment by LostInDarkMath** [comment]
You can avoid these many arguments right now. That was the main reason why I added support for `**kwargs`. Runnable example:

```python
import json

import flask
from flask import jsonify
from flask_restful import Api

from flask_request_validator import validate_params, Param, MinLength, Enum, JSON

app = flask.Flask(__name__)
test_api = Api(app, '/v1')


ValidRequest = [
    Param('first_name', JSON, str, rules=[MinLength(1)]),
    Param('street', JSON, list),
    Param('country', JSON, str, rules=[Enum('Germany')]),
    Param('meta', JSON, dict),
]


@app.route('/example')
@validate_params(*ValidRequest)
def example(**kwargs):
      print(kwargs)
      return jsonify(kwargs)


with app.test_client() as client:
    data = {
        'first_name': 'Egon',
        'street': ['a', 'b'],
        'country': 'Germany',
        'meta': {'hello': 42},
    }
    res = client.get('/example', data=json.dumps(data), content_type='application/json')
    print(res)
```

**Comment by d-ganchar** [comment]
@LostInDarkMath I'm agree with you. Let's leave it as it is now.
