### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by vermaat** [d-ganchar/flask_request_validator#40]
When using 'pip install flask_request_validator'

results into:
'''
Collecting flask_request_validator
  Downloading https://files.pythonhosted.org/packages/0f/6f/4ae63b0227fc8de1ea6639d9b43123a2a4af8ea2caa2de254f7325ab2a2a/flask_request_validator-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5v/6yq9wvj94q3btmbrr5l5vs9h0000gn/T/pip-install-vfcemjt3/flask-request-validator/setup.py", line 2, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'
'''

**Comment by vermaat** [comment]
After installing 'pypandoc' I het the following error when using pip install flask_request_validator':


  Using cached https://files.pythonhosted.org/packages/0f/6f/4ae63b0227fc8de1ea6639d9b43123a2a4af8ea2caa2de254f7325ab2a2a/flask_request_validator-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    /private/var/folders/5v/6yq9wvj94q3btmbrr5l5vs9h0000gn/T/pip-install-aihqkoky/flask-request-validator/setup.py:7: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
      long_description = pypandoc.convert('README.md', 'rst')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5v/6yq9wvj94q3btmbrr5l5vs9h0000gn/T/pip-install-aihqkoky/flask-request-validator/setup.py", line 7, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/Users/mickvermaat/Documents/GitHub/howbusyco/hbenv/lib/python3.7/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5v/6yq9wvj94q3btmbrr5l5vs9h0000gn/T/pip-install-aihqkoky/flask-request-validator/

**Comment by vermaat** [comment]
Maybe because I use Python 3.7.3?

**Comment by d-ganchar** [comment]
@vermaat Hello. Thanks for your issue. I think yes... Because [I didn't check Python 3.7](https://github.com/d-ganchar/flask_request_validator/blob/master/.travis.yml#L3)

**Comment by kurtwheeler** [comment]
I get the same error with python 3.6:

```
(venv) kurt@kurtputer:~/Development/python-flask-demo$ pip3 install -r requirements.txt 
Requirement already satisfied: flask in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: SQLAlchemy in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: alembic in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: Flask-SQLAlchemy in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: Flask-Migrate in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: psycopg2-binary in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pypandoc in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Collecting flask-request-validator (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/0f/6f/4ae63b0227fc8de1ea6639d9b43123a2a4af8ea2caa2de254f7325ab2a2a/flask_request_validator-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b9g3h8pj/flask-request-validator/setup.py", line 7, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/home/kurt/Development/python-flask-demo/venv/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b9g3h8pj/flask-request-validator/
(venv) kurt@kurtputer:~/Development/python-flask-demo$ pip3 --version
pip 9.0.1 from /home/kurt/Development/python-flask-demo/venv/lib/python3.6/site-packages (python 3.6)
```

**Comment by kurtwheeler** [comment]
I was able to install version 2.0.0! Not sure what changed in the most recent version, but 2.0.0 installed simply enough.

**Comment by AaronForce1** [comment]
Recommend v2.1 actually. v2.1.1 is messed up - this PR should hopefully repair it.

**Comment by d-ganchar** [comment]
uploaded into **pypi**
