### ISSUE TITLE
Http status code question

### ISSUE THREAD

**Issue by mauricioalarcon** [d-ganchar/flask_request_validator#43]
First of all, thanks for putting this library together. I was following the examples on the readme and I noticed that all validations are returning 500 instead of a 400 or 422 that is more appropriate for client errors.

Is there a way to control the response status per validation?

**Comment by d-ganchar** [comment]
@mauricioalarcon hi. thank you. 
You can catch any [exception](https://github.com/d-ganchar/flask_request_validator/blob/master/flask_request_validator/exceptions.py) easily using [errorhandler](https://flask.palletsprojects.com/en/1.1.x/errorhandling/#generic-exception-handlers). So you can change any status or set any metadata into `json` or render any error page. 
Is it what you need?

**Comment by mauricioalarcon** [comment]
@d-ganchar Thanks for getting back to me; yes, errorhandler seems the way to go.
