### ISSUE TITLE
documentation error: Param default is misnamed

### ISSUE THREAD

**Issue by fredhope2000** [d-ganchar/flask_request_validator#44]
The README states that default values can be set using `default_value`, in the line that says:
```
default_value, None by default. You can use lambda for this arg - default=lambda: ['test']
```
but it should actually be `default` (https://github.com/d-ganchar/flask_request_validator/blob/80231652990a2c2c0541118bb44265594e9a5897/flask_request_validator/validator.py#L24). (Though the lambda note at the end of the line has it correct.)

**Comment by d-ganchar** [comment]
@fredhope2000 as far as I understand this applies to all parameters?(`required_or_no`, `type_of_value` etc). can you provide your example?

**Comment by fredhope2000** [comment]
Oh yeah you're right, it applies to all of them. I only noticed it for `default` because I tried using it as a kwarg and got an error.
