### ISSUE TITLE
How would one handle a resource with multiple methods?

### ISSUE THREAD

**Issue by PeteW** [d-ganchar/flask_request_validator#53]
Consider the following resource widgets which supports multiple methods. The validation required varies by method.
```
@app.route('/1.0/widgets', methods=['GET', 'DELETE', 'PUT'])
```

**Comment by LostInDarkMath** [comment]
As far as I know, this is currently not supported. The only thing you can do here is to split the endpoint and create one endpoint for each request method:

```python
@app.route('/1.0/widgets', methods=['GET'])
def get_widgets(...):
    pass

@app.route('/1.0/widgets', methods=['DELETE'])
def get_widgets(...):
    pass

@app.route('/1.0/widgets', methods=['PUT'])
def get_widgets(...):
    pass
```

**Comment by d-ganchar** [comment]
@LostInDarkMath you are right 😉 
@PeteW different requests has different parameters and responses in most cases. I'm sure that 1 route for all cases is uncomfortable. Let's see:
```
@app.route('/1.0/widgets', methods=['GET', 'DELETE', 'PUT', 'POST'])
def widgets():
        if request.method == 'POST':
                # blablabla... return response1
        if request.method == 'GET':
                # blablabla... return response2
        if request.method == 'PUT':
                # blablabla... return response3
        if request.method == 'DELETE':
               # blablabla... return response4
```
     
it seems to me that 4 different functions with parameter descriptions is a more elegant approach.

**Comment by PeteW** [comment]
Agreed. I'm someone new to flask and I was surprised to find that every example I could find lumped all HTTP methods into the same function. I was sort of misguided to believe that this was a preferred practice in flask. Dividing each HTTP method into its own function with different routes is far more sane.

Thanks for sharing.
