### ISSUE TITLE
BUG conflict of identical parameter names

### ISSUE THREAD

**Issue by d-ganchar** [d-ganchar/flask_request_validator#55]
**Description**
the validator ignores a parameter types and considers only names. only one parameter is passed into the route after validation when multiple types with the same name. it's not obvious.

**To Reproduce**
```
@app.route('/user/<string:user>', methods=['POST'])
@validate_params(
    Param('user', PATH, str),
    Param('user', JSON, str),
)
def user(**kwargs):
    # PATH parameter not passed into route. the same situation will be with other parameters(GET, HEADER)
    # especially interesting when using GET parameters. looks like very high critical bug
    print(kwargs)  # {'user': 'Willi Sontopski'} 
    return 'ok'
```
`curl`:
```
curl --header "Content-Type: application/json" \
                          --request POST \
                          --data '{"user":"Willi Sontopski"}' \
                          http://localhost:5000/user/w_sontopski
```

**Environment**
 - `flask_request_validator` any
 - `python` any
 - `Flask` any

**Expected behavior**
separate names by type. I think that the argument of route should be an instance instead of `**kwargs`. Example:

```
def user(valid):
    print(valid.get_path())  # dict
    print(valid.get_headers())  # dict
    print(valid.get_json())  # dict
    print(valid.get_form())  # dict
```

**Comment by LostInDarkMath** [comment]
I'll have a look at this later. My personal opinion is that parameter names should be unique.

**Comment by d-ganchar** [comment]
> I'll have a look at this later. My personal opinion is that parameter names should be unique.

In any case, I think better throw an error when duplicate names.
