### ISSUE TITLE
Upcoming version 4.0.0 should be backward compatible to 3.0.x

### ISSUE THREAD

**Issue by LostInDarkMath** [d-ganchar/flask_request_validator#60]
As I mentioned in the latest pull request I think would be great to keep backward compatibility. I understand your idea behind raising exceptions in rules. Look at this examples:

## Version 3.0.x
```python
class ContainsDog(AbstractRule):
    def validate(self, value: str) -> Tuple[str, List[str]]:
        errors = []

        if 'dog' not in value.lower():
            errors.append('no dog found')

        return value, errors
```
## Version 4.0.x
```python
class ContainsDog(AbstractRule):
    def validate(self, value: str) -> str:
        if 'dog' != value.lower():
            raise RuleError('invalid dog')
        return value
```

Maybe we can find a compromise and allow both implementions? Something like this maybe could do the trick:
```python
class AbstractRule(ABC):

   def validate_wrapper(self, value: Any) -> Any:
       res = self.validate(value)
       
       if len(res) == 2:
          raise RuleError(res[1])

       return res

    @abstractmethod
    def validate(self, value: Any) -> Union[Any, Tuple[Any, List[str]]]:
        pass
```

**Comment by d-ganchar** [comment]
No. This is not the only problem:

- we have different [errors](https://github.com/d-ganchar/flask_request_validator/blob/release/4.0.0/flask_request_validator/exceptions.py)
- we have no [**kwargs](https://github.com/d-ganchar/flask_request_validator/blob/release/4.0.0/flask_request_validator/valid_request.py) in routes

By the way, I don't understand what this is for. Look at `Rules`. Each [Rule](https://github.com/d-ganchar/flask_request_validator/blob/release/4.0.0/flask_request_validator/rules.py) has only 1 `error` and this is logical. `list` make sens only when `CustomRule`. But you can do the same trick using [ListRuleError](https://github.com/d-ganchar/flask_request_validator/pull/57#issuecomment-760187118). You will get the same effect. I'm sure that changing a `custom rules` to the new format isn't a difficult task. 
Yes, maybe I should add `ListRuleError` into the package errors. Here I agree.

**Comment by d-ganchar** [comment]
@LostInDarkMath [ListRuleError added](https://github.com/d-ganchar/flask_request_validator/commit/4cb836d3495ef55c43a080ed923d3f040a9d2e2a)

**Comment by LostInDarkMath** [comment]
Okay, I understand.
