### ISSUE TITLE
BUG: Error when PATH parameter is valid

### ISSUE THREAD

**Issue by acontass** [d-ganchar/flask_request_validator#72]
**Description**
Get this error when PATH parameter is valid: `TypeError: got multiple values for argument`.

It seems this is due to lines **164-165** on **validator.py**:
```
return func(*args, **kwargs)
```
But i don't found the solution to fix it for now. Any idea ?

**To Reproduce**

Route:

```python
@app.route("/<int:test>", methods=["GET"])
@validate_params(Param('test', PATH, int))
def produce_error(test):
    return {"value": test}, 200
```

cURL:

```bash
curl --request GET \
  --url http://127.0.0.1:5000/1
```

**Environment**
 - `flask_request_validator` 4.0.3
 - `python` 3.9.4

**Expected behavior**
```json
{"value": 1}
```

**Comment by d-ganchar** [comment]
Hello. Thank you for your report.

v4 no longer has [args, kwargs](https://github.com/d-ganchar/flask_request_validator/wiki/v3-to-v4#the-reason-for-incompatibility). 
[validator.py 174](https://github.com/d-ganchar/flask_request_validator/blob/master/flask_request_validator/validator.py#L174) has no `return func(*args, **kwargs)`. Are you sure that you are using v4?

**Comment by acontass** [comment]
Hello.

Yes it is the v4, on the other hand I made a mistake on the number of the line, it is the [164-165](https://github.com/d-ganchar/flask_request_validator/blob/03f83db7e129666273dc2a31ff03e15b991b33d2/flask_request_validator/validator.py#L164). Sorry for the mistake.

**Comment by d-ganchar** [comment]
@acontass Not sure that is bug. The main problem is that I [left](https://github.com/d-ganchar/flask_request_validator/blob/master/tests/test_validator.py#L42) the `PATH` parameters as arguments. 
hm🤔... I don't remember why I chose this way. So here is an example for your case:

```
@app.route('/issue_72/<int:test>', methods=['GET'])
@validate_params(Param('test', PATH, int))
def issue_72(req: ValidRequest, test):
    return flask.jsonify({'params': req.get_path_params()})
```

Anyway thank you one more time.

**Comment by acontass** [comment]
@d-ganchar Yes it works, thank you 🙏 .

Good work for this lightweight and clear package !

Have a nice day.
