### ISSUE TITLE
QSTN: How to use this library to validate array/list as part of POST request?

### ISSUE THREAD

**Issue by ParagMeshram** [d-ganchar/flask_request_validator#74]
My API supports bulk insert of the records and accepts a list as part of the API request body -

```bash
curl --request POST \
  --url http://127.0.0.1:8080/api/v1/employees \
  --header 'content-type: application/json' \
  --data '[{"name": "Gloria Lamb","age": 25},{"name": "Travis Mathis","age": 38}]'
```

```python
  
@app.route('employees', methods=['POST'])
@validate_params(
    Param('', JSON, list), # ???
)
def add_employees():
    ...
    ...
```

I have been trying to do this but I believe it is not currently supported. I can not modify the API request to just include a property to hold the list of employees. Is it possible to implement the same using the flask_request_validator?

If yes, please suggest how I can implement such validation?

**Comment by d-ganchar** [comment]
Hello. Thank you for your question.
hm... 🤔 Good point. Currently it's impossible to validate a list of items without a key. I think I'll add support in the future. There is no time now.

As quick fix you can use `JsonParam` + `as_list` flag:

```
# --data '{"employees":[{"name": "Gloria Lamb","age": 25},{"name": "Travis Mathis","age": 16}]}'
@app.route('/', methods=['POST'])
@validate_params(
    JsonParam({
        'employees': JsonParam({
            'age': [Number()],
            'name': [MinLength(3), MaxLength(20)],
        }, as_list=True,),
    }, )
)
def home(valid: ValidRequest):
    return jsonify(valid.get_json())
```

**Comment by ParagMeshram** [comment]
@d-ganchar thanks for the response. I would wait for the feature 👍🏻

**Comment by d-ganchar** [comment]
@ParagMeshram example:

```
employees_params = [
    JsonParam({
        'age': [Number()],
        'name': [MinLength(3), MaxLength(20)],
    }, as_list=True)
]


@app.route('/employees', methods=['POST'])
@validate_params(*employees_params)
def employees(valid: ValidRequest):
    return jsonify(valid.get_json())
```

jfyi: [2 errors](https://github.com/d-ganchar/flask_request_validator/pull/78/commits/328c37717405239ad825aa864f8553eba6a4f83d#diff-93819741da2a8b9b098aa3b6af90b90616b1d71987c4207836c7ecc161f39ba0R25) added
