### ISSUE TITLE
Support for Flask 2.X.X?

### ISSUE THREAD

**Issue by PeteW** [d-ganchar/flask_request_validator#79]
I noticed the requirements.txt indicates a dependency on Flask 1.0.0
Is this library compatible with Flask 2.X.X? At this point the Flask V1.X arent receiving further support which puts users in a position searching for an upgrade.

**Comment by LostInDarkMath** [comment]
Hi @PeteW!
This package also works fine with the latest versions of `Flask` and `Werkzeug`. If you face any issues please feel free to open an issue :)
