### ISSUE TITLE
QSTN: JsonParam int validation

### ISSUE THREAD

**Issue by choonyme** [d-ganchar/flask_request_validator#83]
Is there a way to validate an int property with JsonParam? So far I can only pass in CompositeRules but nothing other than that.
For example, 

@validate_params(
    JsonParam({
        'namespace': [int], 
        'key': [MinLength(1), MaxLength(255)], 
        'value': [MaxLength(255)] }, required=True, as_list=True)
)

This 'namespace' type would result in an error. Let me know if there's a way to achieve this. Thanks.

**Comment by d-ganchar** [comment]
@choonyme Hello 👋
Thank you for your question. I'll let you know next week

**Comment by d-ganchar** [comment]
@choonyme could you show the data structure please?

**Comment by choonyme** [comment]
> @choonyme could you show the data structure please?

It's
[
   {
      "namespace": "test1",   <---- how to verify this as string?
      "key": "test1key",
      "value": "test1value',
    },
   {
      "namespace": "test2",
      "key": "test2key",
      "value": "test2value',
    },
]

**Comment by d-ganchar** [comment]
@choonyme published. I'll [update docs](https://github.com/d-ganchar/flask_request_validator/commit/297b4c8283a38a345bfd1be0d916e72b55331893#diff-ec9c3629c75e5d76143939154a945c97ca3a96b297b5aa256d9199013755aa6bR243) later. I'm really very busy

**Comment by d-ganchar** [comment]
[rules](https://github.com/d-ganchar/flask_request_validator/wiki/Rules/632462ba438f7d3b5ce2b99a1f146c714ef8c8c7)
[release](https://github.com/d-ganchar/flask_request_validator/releases/tag/v4.3.0)
