### ISSUE TITLE
QSTN: Is it possible to validate files from request

### ISSUE THREAD

**Issue by William-Depix** [d-ganchar/flask_request_validator#85]
Is it possible to validate uploaded files? For example, checking how many files are being uploaded in the request, what are their file types and the files' size. 

I have some images appended in the form data to pass into the request. Is there any way to validate their amount, file types and file size?

Thank you!

**Comment by d-ganchar** [comment]
@William-Depix  Hello. Thank you for the question.
Сurrently no ( But the idea is great. I'll be very busy for a couple of months and I have no opportunity to implement this sooner. Sorry 😔

You can add functionality if you need it faster. But we need to think about the format.

**Comment by William-Depix** [comment]
Got it. Thanks for the info!

**Comment by d-ganchar** [comment]
@William-Depix, @LostInDarkMath  hey! I'm thinking about the format and wanted to know your vision.
So here is an example for multiple uploading:
```
@app.route('/files', methods=['POST'])
@validate_params(
    FileChain(
        mime_types=['application/pdf', 'image/jpeg'], 
        max_size=1024 * 1024, 
        max_files=3,          
        name_pattern=r'^....$' # optional
    )
)
```

Validation by file names:

```
@app.route('/files', methods=['POST'])
@validate_params(
    File(
        mime_type='application/pdf',
        max_size=1024 * 1024,
        name='document',
    ),
    File(
        mime_type='image/jpeg',
        max_size=1024 * 1024,
        name='photo',
    )
)
```

Any suggestions? Wishes?

**Comment by LostInDarkMath** [comment]
I think that the `mime_type` should be an array because in most cases, multiple mime types are allowed.

**Comment by d-ganchar** [comment]
@William-Depix published. I'll [update docs](https://github.com/d-ganchar/flask_request_validator/commit/8c5fffac53e81540b1e15fc8fdfba4244beb8b65#diff-b896191b486d7f82878411eba67be62d8aaf61db51f3952661e4bd947f6ed8c4) later. I'm really very busy

**Comment by William-Depix** [comment]
This looks exactly what I need! Thanks a lot!

**Comment by d-ganchar** [comment]
[rules](https://github.com/d-ganchar/flask_request_validator/wiki/Rules/632462ba438f7d3b5ce2b99a1f146c714ef8c8c7)
[release](https://github.com/d-ganchar/flask_request_validator/releases/tag/v4.3.0)
